name: Version check

on: [push, pull_request]

jobs:
  build-linux:
    name: "Version check"
    runs-on: ubuntu-latest
    steps:
    - name: Download update info
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Run version check
      run: python scripts/check.py ${{ github.ref }}